export { default as Hero } from './Hero.jsx'
export { default as About } from './About.jsx'
export { default as Services } from './Services.jsx'
export { default as Projects } from './Projects.jsx'
export { default as Contact } from './Contact.jsx'
export { default as News } from './News.jsx'
export { default as Default } from './Default.jsx'