export { default as Hero } from './Hero.jsx'
export { default as About } from './About'
export { default as Services } from './Services'
export { default as Projects } from './Projects'
export { default as News } from './News'
export { default as Contact } from './Contact'
export { default as Default } from './Default'